presentation_folder: "90_Streamlit_apps/MWW01/SlideJet_Presentations/SJ_DATA/GWBmC_WS2526_T03_Str\xF6mungsmodellierung"
header_text: "GWBmC_WS2526_T03_Str\xF6mungsmodellierung"
subheader_text: Interactive Slideshow
