presentation_folder: 90_Streamlit_apps/BGR26/SJ_DATA/2026_03_03_RinnenGRM
header_text: Workshop Grundwassermodellierung 3.Maerz 2026 (BGR Cottbus)
subheader_text: Folien zur Praesentation mit Notizen
