presentation_folder: 90_Streamlit_apps/Courses/SlideJet_Presentations/SJ_DATA/2026_05_05_NuMo_T5_Liedl_Reimann_publish
header_text: 'Grundwassermodellierung Teil 5: Ausblick'
subheader_text: "Interaktive Pr\xE4sentation"
