presentation_folder: 90_Streamlit_apps/Courses/SlideJet_Presentations/SJ_DATA/2026_05_05_NuMo_T1_Liedl_Reimann_publish
header_text: "Grundwassermodellierung Teil1: Organisation, \xDCberblick und Einf\xFC\
  hrung"
subheader_text: "Interactive Pr\xE4sentation"
